# Generated by Django 4.2 on 2025-02-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_price', models.CharField(max_length=10)),
                ('sub_time_limit', models.CharField(max_length=20)),
            ],
        ),
    ]
