# Generated by Django 4.2 on 2025-02-16 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_method', models.CharField(choices=[('Card', 'Card'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking')], max_length=50)),
                ('card_no', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('cvv_code', models.CharField(blank=True, max_length=4, null=True)),
                ('card_holder_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscription')),
            ],
        ),
    ]
