# Generated by Django 4.2 on 2025-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_subscription_sub_price_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
