# Generated by Django 4.2 on 2025-02-18 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_star', models.CharField(max_length=100)),
                ('movie_rating', models.CharField(max_length=100)),
                ('movie_duration', models.CharField(max_length=100)),
                ('movie_release_date', models.CharField(max_length=100)),
                ('movie_image', models.ImageField(upload_to='images/')),
                ('movie_video', models.FileField(blank=True, null=True, upload_to='movies/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='app.categories')),
            ],
        ),
    ]
