# Generated by Django 4.2 on 2025-02-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sub_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
