# Generated by Django 5.2.6 on 2025-11-18 12:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cvv_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_holder_nm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(choices=[('CARD', 'Credit / Debit Card'), ('UPI', 'UPI'), ('NETBANKING', 'Net Banking')], default='CARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.subscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.user'),
        ),
    ]
