# Generated by Django 5.2.6 on 2025-11-18 13:14

import random
import string

import app.models
import django.utils.timezone
from django.db import migrations, models


def _generate_temp_txn_id(length=12):
    chars = string.ascii_uppercase + string.digits
    return ''.join(random.choices(chars, k=length))


def populate_unique_transaction_ids(apps, schema_editor):
    Payment = apps.get_model('app', 'Payment')
    existing = set()
    for payment in Payment.objects.all().order_by('pk'):
        txn = payment.transaction_id or ''
        if not txn or txn in existing:
            txn = _generate_temp_txn_id()
            while txn in existing:
                txn = _generate_temp_txn_id()
            payment.transaction_id = txn
            payment.save(update_fields=['transaction_id'])
        existing.add(txn)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_payment_amount_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RunPython(populate_unique_transaction_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=app.models.generate_transaction_id, editable=False, max_length=20, unique=True),
        ),
    ]
