# Generated by Django 5.2.6 on 2025-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_payment_amount_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('star_id', models.AutoField(primary_key=True, serialize=False)),
                ('star_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('star_photo', models.ImageField(help_text='Star profile photo', upload_to='stars/photos/')),
                ('star_background', models.ImageField(blank=True, help_text='Background image for star profile', null=True, upload_to='stars/backgrounds/')),
                ('star_bio', models.TextField(blank=True, help_text='Biography or description of the star', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
                'ordering': ['star_name'],
                'indexes': [models.Index(fields=['star_name'], name='app_star_star_na_7b01c3_idx')],
            },
        ),
    ]
