# Generated by Django 5.2.3 on 2025-11-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_options_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('new_release', 'New Release'), ('special_screening', 'Special Screening'), ('free_stream', 'Limited-Time Free Stream')], default='new_release', max_length=32)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='app.movies')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['event_type'], name='app_movieev_event_t_1fed53_idx'), models.Index(fields=['start_time', 'end_time'], name='app_movieev_start_t_ff362e_idx')],
            },
        ),
    ]
