# Generated by Django 5.2.3 on 2025-11-20 17:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_movieevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('usability', 'Usability'), ('bug', 'Bug Report'), ('uiux', 'UI / UX'), ('other', 'Other')], default='usability', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional rating between 1 and 5 to describe overall satisfaction.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_feedback', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating between 1 (lowest) and 5 (highest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_feedback', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_watched', models.PositiveIntegerField(default=1)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_logs', to='app.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='app.user')),
            ],
            options={
                'ordering': ['-last_watched_at'],
                'indexes': [models.Index(fields=['user', 'movie'], name='app_watchhi_user_id_45e5f9_idx'), models.Index(fields=['-last_watched_at'], name='app_watchhi_last_wa_c3d0ee_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
