# Generated by Django 5.2.3 on 2025-11-20 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_appfeedback_moviefeedback_watchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('artist_photo', models.ImageField(help_text='Artist profile photo', upload_to='artists/photos/')),
                ('artist_background', models.ImageField(blank=True, help_text='Background image for artist profile', null=True, upload_to='artists/backgrounds/')),
                ('artist_bio', models.TextField(blank=True, help_text='Biography or description of the artist', null=True)),
                ('category', models.CharField(choices=[('actor', 'Actor'), ('singer', 'Singer'), ('director', 'Director'), ('composer', 'Composer')], default='actor', max_length=20)),
                ('popularity_rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Popularity rating from 0.0 to 10.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_featured', models.BooleanField(default=False, help_text='Show in popular artists section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(blank=True, help_text='Movies associated with this artist', related_name='artists', to='app.movies')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['-popularity_rating', 'artist_name'],
            },
        ),
        migrations.CreateModel(
            name='UserArtistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='app.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_artists', to='app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['artist_name'], name='app_artist_artist__d5b7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['-popularity_rating'], name='app_artist_popular_d9c3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['category'], name='app_artist_categor_e5d28d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userartistfollow',
            unique_together={('user', 'artist')},
        ),
    ]
