# Generated by Django 5.2.3 on 2025-11-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_artist_userartistfollow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('language_code', models.CharField(help_text="ISO language code (e.g., 'hi', 'en', 'ta')", max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show in language selection')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which language appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['display_order', 'language_name'],
                'indexes': [models.Index(fields=['language_name'], name='app_languag_languag_10d5a9_idx'), models.Index(fields=['is_active'], name='app_languag_is_acti_1ecdb3_idx')],
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Primary language of the movie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='app.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.ForeignKey(blank=True, help_text="User's preferred language for recommendations", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.language'),
        ),
    ]
