# Generated by Django 5.2.6 on 2025-11-20 18:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_language_movies_language_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['genre_name'],
            },
        ),
        migrations.CreateModel(
            name='WebSeries',
            fields=[
                ('webseries_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='Short description for cards', max_length=300)),
                ('poster', models.ImageField(upload_to='webseries/posters/')),
                ('age_rating', models.CharField(choices=[('U', 'U - Universal'), ('UA', 'UA - Parental Guidance'), ('A', 'A - Adults Only'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+')], default='U', max_length=10)),
                ('year', models.PositiveIntegerField(help_text='Release year')),
                ('cast', models.CharField(blank=True, help_text='Comma-separated cast names', max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating from 0.0 to 10.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_trending', models.BooleanField(default=False, help_text='Show in trending section')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(blank=True, related_name='webseries', to='app.genre')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webseries', to='app.language')),
            ],
            options={
                'verbose_name': 'Web Series',
                'verbose_name_plural': 'Web Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Video URL or link')),
                ('video_file', models.FileField(blank=True, help_text='Video file upload', null=True, upload_to='webseries/episodes/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='webseries/episodes/thumbnails/')),
                ('duration', models.CharField(blank=True, help_text="Duration in minutes (e.g., '45 min')", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='app.webseries')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['episode_number'],
            },
        ),
        migrations.CreateModel(
            name='WebSeriesLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating between 1 and 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webseries_likes', to='app.user')),
                ('webseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.webseries')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebSeriesWatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_watched', models.PositiveIntegerField(default=1)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_logs', to='app.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webseries_watch_history', to='app.user')),
            ],
            options={
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.CreateModel(
            name='WebSeriesWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webseries_watchlist', to='app.user')),
                ('webseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='app.webseries')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webseries',
            index=models.Index(fields=['title'], name='app_webseri_title_d430a5_idx'),
        ),
        migrations.AddIndex(
            model_name='webseries',
            index=models.Index(fields=['language'], name='app_webseri_languag_431709_idx'),
        ),
        migrations.AddIndex(
            model_name='webseries',
            index=models.Index(fields=['-rating'], name='app_webseri_rating_36fd65_idx'),
        ),
        migrations.AddIndex(
            model_name='webseries',
            index=models.Index(fields=['year'], name='app_webseri_year_665868_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['webseries', 'episode_number'], name='app_episode_webseri_202eb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('webseries', 'episode_number')},
        ),
        migrations.AlterUniqueTogether(
            name='webserieslike',
            unique_together={('user', 'webseries')},
        ),
        migrations.AddIndex(
            model_name='webserieswatchhistory',
            index=models.Index(fields=['user', 'episode'], name='app_webseri_user_id_c1416e_idx'),
        ),
        migrations.AddIndex(
            model_name='webserieswatchhistory',
            index=models.Index(fields=['-last_watched_at'], name='app_webseri_last_wa_5ca453_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webserieswatchhistory',
            unique_together={('user', 'episode')},
        ),
        migrations.AlterUniqueTogether(
            name='webserieswatchlist',
            unique_together={('user', 'webseries')},
        ),
    ]
