# Generated by Django 5.2.6 on 2025-11-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_genre_webseries_episode_webserieslike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_backdrop',
            field=models.ImageField(blank=True, help_text='Optional cinematic background shown on detail page', null=True, upload_to='images/backdrops/'),
        ),
        migrations.AddField(
            model_name='webseries',
            name='backdrop',
            field=models.ImageField(blank=True, help_text='Hero background image for detail page', null=True, upload_to='webseries/backdrops/'),
        ),
    ]
