# Generated by Django 5.2.6 on 2025-11-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_webseries_event_recommendation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webseriesevent',
            new_name='app_webseri_webseri_3cb81c_idx',
            old_name='app_webserie_webseri_9a4590_idx',
        ),
        migrations.RenameIndex(
            model_name='webseriesevent',
            new_name='app_webseri_start_t_b129b8_idx',
            old_name='app_webserie_start_t_cb170a_idx',
        ),
        migrations.RenameIndex(
            model_name='webseriesrecommendation',
            new_name='app_webseri_source__00aaef_idx',
            old_name='app_webserie_source__17e1b0_idx',
        ),
    ]
