# Generated by Django 5.2.3 on 2025-11-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_app_webserie_webseri_9a4590_idx_app_webseri_webseri_3cb81c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking the user', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
