# Generated by Django 5.2.3 on 2026-03-03 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_user_block_reason_user_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSlider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('slider_image', models.ImageField(help_text='Image for the slider card', upload_to='slider/')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slider')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slider_items', to='app.movies')),
            ],
            options={
                'verbose_name': 'Movie Slider',
                'verbose_name_plural': 'Movie Sliders',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
