# Generated by Django 5.2.3 on 2026-03-03 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_movieslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTrailer',
            fields=[
                ('trailer_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(help_text='Upload video trailer', upload_to='trailers/')),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to show on homepage (only the most recent active one will show)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailer_promotions', to='app.movies')),
            ],
            options={
                'verbose_name': 'Home Trailer',
                'verbose_name_plural': 'Home Trailers',
                'ordering': ['-created_at'],
            },
        ),
    ]
