# Generated by Django 5.2.3 on 2026-03-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_hometrailer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeTrailer',
        ),
    ]
