# Generated by Django 6.0.3 on 2026-05-10 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_hometrailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(help_text='Song cover image', upload_to='songs/covers/')),
                ('audio_file', models.FileField(help_text='Upload audio file (mp3, wav)', upload_to='songs/audio/')),
                ('duration', models.CharField(blank=True, help_text="Duration (e.g., '3:45')", max_length=20)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('is_featured', models.BooleanField(default=False)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('singers', models.ManyToManyField(help_text='Select singers', limit_choices_to={'category': 'singer'}, related_name='songs', to='app.artist')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['-release_date'],
            },
        ),
    ]
