# Generated by Django 6.0.3 on 2026-05-10 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Language of the song', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='app.language'),
        ),
    ]
