# Generated by Django 6.0.3 on 2026-05-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_playlist_playlistsong_usersonglike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
            ],
            options={
                'verbose_name': 'Singer',
                'verbose_name_plural': 'Singers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.artist',),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, help_text='Optional lyrics for the song', null=True),
        ),
    ]
